### ISSUE TITLE
Port panels to the editable form

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-plugin#208]
List of panels : 

* [x] Locate by layer #202 
* [x] Attribute table #207 
* [x] Edition : the JSON structure is different about ACL #211
* [x] Tooltip #207 
* [x] Filter by login #203 
* [x] Dataviz #218 
* [x] Time manager : `master` #214 and `dev` #215
* [x] Atlas #193 
* [x] Filter by form, the JSON is different #205

**Comment by Gustry** [comment]
Done !

**Comment by josemvm** [comment]
@Gustry thank you very much for all your work on this plugin!

just a litle note:

did you forget to alternately put gray on the lines for locate, tooltip and time manager?...
did you forget to put the the move up and the move down buttons for tooltip?...

**Comment by Gustry** [comment]
> did you forget to alternately put gray on the lines for locate, tooltip and time manager?...

Done

>  did you forget to put the the move up and the move down buttons for tooltip?...

Done too.

95d6a57

Thanks for your feedbacks. Please create new tickets.
